---
services: docker

env:
- distro: centos6
  version: latest
  init: /sbin/init

- distro: centos7
  init: /usr/lib/systemd/systemd
  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  version: latest

before_install:
  # Pull container
- 'docker pull rndmh3ro/docker-${distro}-ansible:${version}'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/ansible-role-ssh-keys:ro ${run_opts} rndmh3ro/docker-${distro}-ansible:${version} "${init}" > "${container_id}"'

  # Test role.
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/ansible-role-ssh-keys/tests/test.yml'
